#!/bin/bash

# NOTE: you might have to do `ps` on the
# command line to find this process and
# kill it if using CTRL + c doesn't work. 

# This script runs the development 
# version of the process inside the
# `test-site` directory to smoke
# test the output

if [ -d "test-site" ]; then
  rm -rf "test-site"
]
fi

mkdir "test-site"

# Adding a .gitignore to the test-site directory
# has been removed for now as it makes the
# file tree disappear in the nvim-tree
# file explorer
#
# echo "*" > "test-site/.gitignore"
# echo "!.gitignore" >> "test-site/.gitignore"

cargo watch -C test-site -q -c -x run


